INSERT INTO 国マスタ(
名称,
正式名称,
名称＿英語,
正式名称＿英語,
首都名称,
コード＿数字3桁,
コード＿英字3文字,
コード＿英字2文字,
地域コード,登録者,更新者
) VALUES
('アイスランド', 'アイスランド共和国', 'Iceland', 'Iceland', 'レイキャヴィーク', '352', 'ISL', 'IS', '09',13,13),
('アイルランド', 'アイルランド', 'Ireland', 'Republic of Ireland', 'ダブリン', '372', 'IRL', 'IE', '10',13,13),
('アゼルバイジャン', 'アゼルバイジャン共和国', 'Azerbaijan', 'Republic of Azerbaijan', 'バクー', '031', 'AZE', 'AZ', '08',13,13),
('アフガニスタン', 'アフガニスタン・イスラム共和国', 'Afghanistan', 'Islamic Republic of Afghanistan', 'カブール', '004', 'AFG', 'AF', '06',13,13),
('アメリカ', 'アメリカ合衆国', 'United States', 'United States of America', 'ワシントンD.C.', '840', 'USA', 'US', '12',13,13),
('アラブ首長国連邦', 'アラブ首長国連邦', 'United Arab Emirates', 'United Arab Emirates', 'アブダビ', '784', 'ARE', 'AE', '06',13,13),
('アルジェリア', 'アルジェリア民主人民共和国', 'Algeria', 'People''s Democratic Republic of Algeria', 'アルジェ', '012', 'DZA', 'DZ', '15',13,13),
('アルゼンチン', 'アルゼンチン共和国', 'Argentina', 'Argentine Republic', 'ブエノスアイレス', '032', 'ARG', 'AR', '14',13,13),
('アルバ', 'アルバ', 'Aruba', 'Country of Aruba', 'オラニエスタッド', '533', 'ABW', 'AW', '13',13,13),
('アルバニア', 'アルバニア共和国', 'Albania', 'Republic of Albania', 'ティラナ', '008', 'ALB', 'AL', '08',13,13),
('アルメニア', 'アルメニア共和国', 'Armenia', 'Republic of Armenia', 'エレバン', '051', 'ARM', 'AM', '08',13,13),
('アンギラ', 'アンギラ', 'Anguilla', 'Anguilla', 'バレー', '660', 'AIA', 'AI', '13',13,13),
('アンゴラ', 'アンゴラ共和国', 'Angola', 'Republic of Angola', 'ルアンダ', '024', 'AGO', 'AO', '19',13,13),
('アンティグア・バーブーダ', 'アンティグア・バーブーダ', 'Antigua and Barbuda', 'Antigua and Barbuda', 'セントジョンズ', '028', 'ATG', 'AG', '13',13,13),
('アンドラ', 'アンドラ公国', 'Andorra', 'Principality of Andorra', 'アンドラ・ラ・ベリャ', '020', 'AND', 'AD', '10',13,13),
('イエメン', 'イエメン共和国', 'Yemen', 'Republic of Yemen', 'サナア', '887', 'YEM', 'YE', '06',13,13),
('イギリス', 'グレートブリテン及び北アイルランド連合王国', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'ロンドン', '826', 'GBR', 'GB', '10',13,13),
('イギリス領インド洋地域', 'イギリス領インド洋地域', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'ヴィクトリア', '086', 'IOT', 'IO', '04',13,13),
('イスラエル', 'イスラエル国', 'Israel', 'State of Israel', 'エルサレム[1]', '376', 'ISR', 'IL', '06',13,13),
('イタリア', 'イタリア共和国', 'Italy', 'Italian Republic', 'ローマ', '380', 'ITA', 'IT', '10',13,13),
('イラク', 'イラク共和国', 'Iraq', 'Republic of Iraq', 'バグダード', '368', 'IRQ', 'IQ', '06',13,13),
('イラン', 'イラン・イスラム共和国', 'Iran', 'Islamic Republic of Iran', 'テヘラン', '364', 'IRN', 'IR', '06',13,13),
('インド', 'インド', 'India', 'Republic of India', 'ニューデリー', '356', 'IND', 'IN', '03',13,13),
('インドネシア', 'インドネシア共和国', 'Indonesia', 'Republic of Indonesia', 'ジャカルタ', '360', 'IDN', 'ID', '02',13,13),
('ヴァージン諸島', 'イギリス領ヴァージン諸島', 'Virgin Islands', 'Virgin Islands (British)', 'ロードタウン', '092', 'VGB', 'VG', '13',13,13),
('ヴァージン諸島', 'アメリカ領ヴァージン諸島', 'Virgin Islands', 'Virgin Islands (U.S.)', 'シャーロット・アマリー', '850', 'VIR', 'VI', '13',13,13),
('ウォリス・フツナ', 'ウォリス・フツナ', 'Wallis and Futuna', 'Wallis and Futuna', 'マタウトゥ', '876', 'WLF', 'WF', '20',13,13),
('ウガンダ', 'ウガンダ共和国', 'Uganda', 'Republic of Uganda', 'カンパラ', '800', 'UGA', 'UG', '18',13,13),
('ウクライナ', 'ウクライナ', 'Ukraine', 'Ukraine', 'キエフ', '804', 'UKR', 'UA', '08',13,13),
('ウズベキスタン', 'ウズベキスタン共和国', 'Uzbekistan', 'Republic of Uzbekistan', 'タシュケント', '860', 'UZB', 'UZ', '05',13,13),
('ウルグアイ', 'ウルグアイ東方共和国', 'Uruguay', 'Oriental Republic of Uruguay', 'モンテビデオ', '858', 'URY', 'UY', '14',13,13),
('エクアドル', 'エクアドル共和国', 'Ecuador', 'Republic of Ecuador', 'キト', '218', 'ECU', 'EC', '14',13,13),
('エジプト', 'エジプト・アラブ共和国', 'Egypt', 'Arab Republic of Egypt', 'カイロ', '818', 'EGY', 'EG', '15',13,13),
('エストニア', 'エストニア共和国', 'Estonia', 'Republic of Estonia', 'タリン', '233', 'EST', 'EE', '08',13,13),
('エスワティニ', 'エスワティニ王国', 'Eswatini', 'Kingdom of Eswatini', 'ムババーネ', '748', 'SWZ', 'SZ', '19',13,13),
('エチオピア', 'エチオピア連邦民主共和国', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'アディスアベバ', '231', 'ETH', 'ET', '16',13,13),
('エリトリア', 'エリトリア国', 'Eritrea', 'State of Eritrea', 'アスマラ', '232', 'ERI', 'ER', '16',13,13),
('エルサルバドル', 'エルサルバドル共和国', 'El Salvador', 'Republic of El Salvador', 'サンサルバドル', '222', 'SLV', 'SV', '13',13,13),
('オーストラリア', 'オーストラリア連邦', 'Australia', 'Commonwealth of Australia', 'キャンベラ', '036', 'AUS', 'AU', '20',13,13),
('オーストリア', 'オーストリア共和国', 'Austria', 'Republic of Austria', 'ウィーン', '040', 'AUT', 'AT', '08',13,13),
('オーランド諸島', 'オーランド諸島', 'Åland Islands', 'Åland Islands', 'マリエハムン', '248', 'ALA', 'AX', '09',13,13),
('オマーン', 'オマーン国', 'Oman', 'Sultanate of Oman', 'マスカット', '512', 'OMN', 'OM', '06',13,13),
('オランダ', 'オランダ王国', 'Netherlands', 'Kingdom of the Netherlands', 'アムステルダム', '528', 'NLD', 'NL', '10',13,13),
('ガーナ', 'ガーナ共和国', 'Ghana', 'Republic of Ghana', 'アクラ', '288', 'GHA', 'GH', '17',13,13),
('カーボベルデ', 'カーボベルデ共和国', 'Cape Verde', 'Republic of Cabo Verde', 'プライア', '132', 'CPV', 'CV', '17',13,13),
('ガーンジー', 'ガーンジー', 'Guernsey', 'Guernsey', 'セント・ピーター・ポート', '831', 'GGY', 'GG', '10',13,13),
('ガイアナ', 'ガイアナ共和国', 'Guyana', 'Co-operative Republic of Guyana', 'ジョージタウン', '328', 'GUY', 'GY', '14',13,13),
('カザフスタン', 'カザフスタン共和国', 'Kazakhstan', 'Republic of Kazakhstan', 'ヌルスルタン', '398', 'KAZ', 'KZ', '05',13,13),
('カタール', 'カタール国', 'Qatar', 'State of Qatar', 'ドーハ', '634', 'QAT', 'QA', '06',13,13),
('合衆国領有小離島', '合衆国領有小離島', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'なし', '581', 'UMI', 'UM', '20',13,13),
('カナダ', 'カナダ', 'Canada', 'Canada', 'オタワ', '124', 'CAN', 'CA', '12',13,13),
('ガボン', 'ガボン共和国', 'Gabon', 'Gabonese Republic', 'リーブルヴィル', '266', 'GAB', 'GA', '18',13,13),
('カメルーン', 'カメルーン共和国', 'Cameroon', 'Republic of Cameroon', 'ヤウンデ', '120', 'CMR', 'CM', '18',13,13),
('韓国', '大韓民国', 'Korea, South', 'Republic of Korea', 'ソウル', '410', 'KOR', 'KR', '01',13,13),
('ガンビア', 'ガンビア共和国', 'Gambia, The', 'Republic of The Gambia', 'バンジュール', '270', 'GMB', 'GM', '17',13,13),
('カンボジア', 'カンボジア王国', 'Cambodia', 'Kingdom of Cambodia', 'プノンペン', '116', 'KHM', 'KH', '02',13,13),
('ギアナ', 'フランス領ギアナ', 'French Guiana', 'French Guiana', 'カイエンヌ', '254', 'GUF', 'GF', '14',13,13),
('北朝鮮', '朝鮮民主主義人民共和国', 'Korea, North', 'Democratic People''s Republic of Korea', '平壌', '408', 'PRK', 'KP', '01',13,13),
('北マケドニア', '北マケドニア共和国', 'North Macedonia', 'Republic of North Macedonia', 'スコピエ', '807', 'MKD', 'MK', '08',13,13),
('北マリアナ諸島', '北マリアナ諸島', 'Northern Mariana Islands', 'Turkish Republic of Northern Cyprus', 'ススペ', '580', 'MNP', 'MP', '20',13,13),
('ギニア', 'ギニア共和国', 'Guinea', 'Republic of Guinea', 'コナクリ', '324', 'GIN', 'GN', '17',13,13),
('ギニアビサウ', 'ギニアビサウ共和国', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'ビサウ', '624', 'GNB', 'GW', '17',13,13),
('キプロス', 'キプロス共和国', 'Cyprus', 'Republic of Cyprus', 'ニコシア', '196', 'CYP', 'CY', '11',13,13),
('キューバ', 'キューバ共和国', 'Cuba', 'Republic of Cuba', 'ハバナ', '192', 'CUB', 'CU', '13',13,13),
('キュラソー', 'キュラソー', 'Curaçao', 'Curaçao', 'ウィレムスタット', '531', 'CUW', 'CW', '13',13,13),
('ギリシャ', 'ギリシャ共和国', 'Greece', 'Hellenic Republic', 'アテネ', '300', 'GRC', 'GR', '10',13,13),
('キリバス', 'キリバス共和国', 'Kiribati', 'Republic of Kiribati', 'タラワ', '296', 'KIR', 'KI', '20',13,13),
('キルギス', 'キルギス共和国', 'Kyrgyzstan', 'Kyrgyz Republic', 'ビシュケク', '417', 'KGZ', 'KG', '05',13,13),
('グアテマラ', 'グアテマラ共和国', 'Guatemala', 'Republic of Guatemala', 'グアテマラシティ', '320', 'GTM', 'GT', '13',13,13),
('グアドループ', 'グアドループ', 'Guadeloupe', 'Guadeloupe', 'バステール', '312', 'GLP', 'GP', '13',13,13),
('グアム', 'グアム', 'Guam', 'Guam', 'ハガニア', '316', 'GUM', 'GU', '20',13,13),
('クウェート', 'クウェート国', 'Kuwait', 'State of Kuwait', 'クウェート', '414', 'KWT', 'KW', '06',13,13),
('クック諸島', 'クック諸島', 'Cook Islands', 'Member of eight UN specialized agencies', 'アバルア', '184', 'COK', 'CK', '20',13,13),
('グリーンランド', 'グリーンランド', 'Greenland', 'Greenland', 'ヌーク', '304', 'GRL', 'GL', '09',13,13),
('クリスマス島', 'クリスマス島', 'Christmas Island', 'Christmas Island', 'フライング・フィッシュ・コーブ', '162', 'CXR', 'CX', '20',13,13),
('グレナダ', 'グレナダ', 'Grenada', 'Grenada', 'セントジョージズ', '308', 'GRD', 'GD', '13',13,13),
('クロアチア', 'クロアチア共和国', 'Croatia', 'Republic of Croatia', 'ザグレブ', '191', 'HRV', 'HR', '08',13,13),
('ケイマン諸島', 'ケイマン諸島', 'Cayman Islands', 'Cayman Islands', 'ジョージタウン', '136', 'CYM', 'KY', '13',13,13),
('ケニア', 'ケニア共和国', 'Kenya', 'Republic of Kenya', 'ナイロビ', '404', 'KEN', 'KE', '16',13,13),
('コートジボワール', 'コートジボワール共和国', 'Ivory Coast', 'Republic of Côte d''Ivoire', 'ヤムスクロ', '384', 'CIV', 'CI', '17',13,13),
('ココス諸島', 'ココス（キーリング）諸島', 'Cocos Islands', 'Cocos Islands', 'ウェスト島', '166', 'CCK', 'CC', '04',13,13),
('コスタリカ', 'コスタリカ共和国', 'Costa Rica', 'Republic of Costa Rica', 'サンホセ', '188', 'CRI', 'CR', '13',13,13),
('コソボ', 'コソボ共和国', 'Kosovo', 'Republic of Kosovo', 'プリシュティナ', '-', '-', '-', '08',13,13),
('コモロ', 'コモロ連合', 'Comoros', 'Union of the Comoros', 'モロニ', '174', 'COM', 'KM', '04',13,13),
('コロンビア', 'コロンビア共和国', 'Colombia', 'Republic of Colombia', 'ボゴタ', '170', 'COL', 'CO', '14',13,13),
('コンゴ', 'コンゴ共和国', 'Congo', 'Democratic Republic of the Congo', 'ブラザヴィル', '178', 'COG', 'CG', '18',13,13),
('コンゴ', 'コンゴ民主共和国', 'Congo, Democratic Republic of the', 'Republic of the Congo', 'キンシャサ', '180', 'COD', 'CD', '18',13,13),
('サウジアラビア', 'サウジアラビア王国', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'リヤド', '682', 'SAU', 'SA', '06',13,13),
('サウスジョージア・サウスサンドウィッチ諸島', 'サウスジョージア・サウスサンドウィッチ諸島', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'キング・エドワード・ポイント', '239', 'SGS', 'GS', '14',13,13),
('サモア', 'アメリカ領サモア', 'Samoa', 'American Samoa', 'パゴパゴ', '016', 'ASM', 'AS', '20',13,13),
('サモア', 'サモア独立国', 'Samoa', 'Independent State of Samoa', 'アピア', '882', 'WSM', 'WS', '20',13,13),
('サン・バルテルミー', 'サン・バルテルミー', 'Saint Barthélemy', 'Saint Barthélemy', 'グスタビア', '652', 'BLM', 'BL', '13',13,13),
('サン・マルタン', 'サン・マルタン（フランス領）', 'Saint Martin', 'Saint Martin (French part)', 'マリゴ', '663', 'MAF', 'MF', '13',13,13),
('サントメ・プリンシペ', 'サントメ・プリンシペ民主共和国', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'サントメ', '678', 'STP', 'ST', '18',13,13),
('ザンビア', 'ザンビア共和国', 'Zambia', 'Republic of Zambia', 'ルサカ', '894', 'ZMB', 'ZM', '19',13,13),
('サンピエール島・ミクロン島', 'サンピエール島・ミクロン島', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'サンピエール', '666', 'SPM', 'PM', '12',13,13),
('サンマリノ', 'サンマリノ共和国', 'San Marino', 'Republic of San Marino', 'サンマリノ', '674', 'SMR', 'SM', '10',13,13),
('シエラレオネ', 'シエラレオネ共和国', 'Sierra Leone', 'Republic of Sierra Leone', 'フリータウン', '694', 'SLE', 'SL', '17',13,13),
('ジブチ', 'ジブチ共和国', 'Djibouti', 'Republic of Djibouti', 'ジブチ', '262', 'DJI', 'DJ', '16',13,13),
('ジブラルタル', 'ジブラルタル', 'Gibraltar', 'Gibraltar', 'ジブラルタル', '292', 'GIB', 'GI', '10',13,13),
('ジャージー', 'ジャージー', 'Jersey', 'Jersey', 'セント・ヘリア', '832', 'JEY', 'JE', '10',13,13),
('ジャマイカ', 'ジャマイカ', 'Jamaica', 'Jamaica', 'キングストン', '388', 'JAM', 'JM', '13',13,13),
('ジョージア', 'ジョージア', 'Georgia', 'Georgia', 'トビリシ', '268', 'GEO', 'GE', '08',13,13),
('シリア', 'シリア・アラブ共和国', 'Syrian', 'Syrian Arab Republic', 'ダマスカス', '760', 'SYR', 'SY', '06',13,13),
('シンガポール', 'シンガポール共和国', 'Singapore', 'Republic of Singapore', 'なし', '702', 'SGP', 'SG', '02',13,13),
('シント・マールテン', 'シント・マールテン（オランダ領）', 'Sint Maarten', 'Sint Maarten (Dutch part)', 'フィリップスブルフ', '534', 'SXM', 'SX', '13',13,13),
('ジンバブエ', 'ジンバブエ共和国', 'Zimbabwe', 'Republic of Zimbabwe', 'ハラレ', '716', 'ZWE', 'ZW', '19',13,13),
('スイス', 'スイス連邦', 'Switzerland', 'Swiss Confederation', 'ベルン', '756', 'CHE', 'CH', '10',13,13),
('スヴァールバル諸島及びヤンマイエン島', 'スヴァールバル諸島及びヤンマイエン島', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'なし', '744', 'SJM', 'SJ', '09',13,13),
('スウェーデン', 'スウェーデン王国', 'Sweden', 'Kingdom of Sweden', 'ストックホルム', '752', 'SWE', 'SE', '09',13,13),
('スーダン', 'スーダン共和国', 'Sudan', 'Republic of the Sudan', 'ハルツーム', '729', 'SDN', 'SD', '16',13,13),
('スペイン', 'スペイン王国', 'Spain', 'Kingdom of Spain', 'マドリード', '724', 'ESP', 'ES', '10',13,13),
('スリナム', 'スリナム共和国', 'Suriname', 'Republic of Suriname', 'パラマリボ', '740', 'SUR', 'SR', '14',13,13),
('スリランカ', 'スリランカ民主社会主義共和国', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'スリジャヤワルダナプラコッテ', '144', 'LKA', 'LK', '03',13,13),
('スロバキア', 'スロバキア共和国', 'Slovakia', 'Slovak Republic', 'ブラチスラバ', '703', 'SVK', 'SK', '08',13,13),
('スロベニア', 'スロベニア共和国', 'Slovenia', 'Republic of Slovenia', 'リュブリャナ', '705', 'SVN', 'SI', '08',13,13),
('セーシェル', 'セーシェル共和国', 'Seychelles', 'Republic of Seychelles', 'ビクトリア', '690', 'SYC', 'SC', '04',13,13),
('赤道ギニア', '赤道ギニア共和国', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'マラボ', '226', 'GNQ', 'GQ', '18',13,13),
('セネガル', 'セネガル共和国', 'Senegal', 'Republic of Senegal', 'ダカール', '686', 'SEN', 'SN', '17',13,13),
('セルビア', 'セルビア共和国', 'Serbia', 'Republic of Serbia', 'ベオグラード', '688', 'SRB', 'RS', '08',13,13),
('セントクリストファー・ネイビス', 'セントクリストファー・ネイビス連邦', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'バセテール', '659', 'KNA', 'KN', '13',13,13),
('セントビンセント及びグレナディーン諸島', 'セントビンセント及びグレナディーン諸島', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'キングスタウン', '670', 'VCT', 'VC', '13',13,13),
('セントヘレナ・アセンション及びトリスタンダクーニャ', 'セントヘレナ・アセンション及びトリスタンダクーニャ', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'ジェームズタウン', '654', 'SHN', 'SH', '17',13,13),
('セントルシア', 'セントルシア', 'Saint Lucia', 'Saint Lucia', 'カストリーズ', '662', 'LCA', 'LC', '13',13,13),
('ソマリア', 'ソマリア連邦共和国', 'Somalia', 'Federal Republic of Somalia', 'モガディシュ', '706', 'SOM', 'SO', '16',13,13),
('ソロモン諸島', 'ソロモン諸島', 'Solomon Islands', 'Solomon Islands', 'ホニアラ', '090', 'SLB', 'SB', '20',13,13),
('タークス・カイコス諸島', 'タークス・カイコス諸島', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'コックバーンタウン', '796', 'TCA', 'TC', '13',13,13),
('タイ', 'タイ王国', 'Thailand', 'Kingdom of Thailand', 'バンコク', '764', 'THA', 'TH', '02',13,13),
('台湾', '中華民国', 'Taiwan', 'Republic of China', '台北', '158', 'TWN', 'TW', '01',13,13),
('タジキスタン', 'タジキスタン共和国', 'Tajikistan', 'Republic of Tajikistan', 'ドゥシャンベ', '762', 'TJK', 'TJ', '05',13,13),
('タンザニア', 'タンザニア連合共和国', 'Tanzania', 'United Republic of Tanzania', 'ドドマ', '834', 'TZA', 'TZ', '16',13,13),
('チェコ', 'チェコ共和国', 'Czechia', 'Czech Republic', 'プラハ', '203', 'CZE', 'CZ', '08',13,13),
('チャド', 'チャド共和国', 'Chad', 'Republic of Chad', 'ンジャメナ', '148', 'TCD', 'TD', '18',13,13),
('中央アフリカ', '中央アフリカ共和国', 'Central African Republic', 'Central African Republic', 'バンギ', '140', 'CAF', 'CF', '18',13,13),
('中国', '中華人民共和国', 'China', 'People''s Republic of China', '北京', '156', 'CHN', 'CN', '01',13,13),
('チュニジア', 'チュニジア共和国', 'Tunisia', 'Republic of Tunisia', 'チュニス', '788', 'TUN', 'TN', '15',13,13),
('チリ', 'チリ共和国', 'Chile', 'Republic of Chile', 'サンティアゴ', '152', 'CHL', 'CL', '14',13,13),
('ツバル', 'ツバル', 'Tuvalu', 'Tuvalu', 'フナフティ', '798', 'TUV', 'TV', '20',13,13),
('デンマーク', 'デンマーク王国', 'Denmark', 'Kingdom of Denmark', 'コペンハーゲン', '208', 'DNK', 'DK', '09',13,13),
('ドイツ', 'ドイツ連邦共和国', 'Germany', 'Federal Republic of Germany', 'ベルリン', '276', 'DEU', 'DE', '10',13,13),
('トーゴ', 'トーゴ共和国', 'Togo', 'Togolese Republic', 'ロメ', '768', 'TGO', 'TG', '17',13,13),
('トケラウ', 'トケラウ', 'Tokelau', 'Tokelau', 'なし', '772', 'TKL', 'TK', '20',13,13),
('ドミニカ', 'ドミニカ国', 'Dominica', 'Commonwealth of Dominica', 'ロゾー', '212', 'DMA', 'DM', '13',13,13),
('ドミニカ', 'ドミニカ共和国', 'Dominican Republic', 'Dominican Republic', 'サントドミンゴ', '214', 'DOM', 'DO', '13',13,13),
('トリニダード・トバゴ', 'トリニダード・トバゴ共和国', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'ポートオブスペイン', '780', 'TTO', 'TT', '13',13,13),
('トルクメニスタン', 'トルクメニスタン', 'Turkmenistan', 'Republic of Turkmenistan', 'アシガバート', '795', 'TKM', 'TM', '05',13,13),
('トルコ', 'トルコ共和国', 'Turkey', 'Republic of Turkey', 'アンカラ', '792', 'TUR', 'TR', '06',13,13),
('トンガ', 'トンガ王国', 'Tonga', 'Kingdom of Tonga', 'ヌクアロファ', '776', 'TON', 'TO', '20',13,13),
('ナイジェリア', 'ナイジェリア連邦共和国', 'Nigeria', 'Federal Republic of Nigeria', 'アブジャ', '566', 'NGA', 'NG', '18',13,13),
('ナウル', 'ナウル共和国', 'Nauru', 'Republic of Nauru', 'ヤレン', '520', 'NRU', 'NR', '20',13,13),
('ナミビア', 'ナミビア共和国', 'Namibia', 'Republic of Namibia', 'ウィントフック', '516', 'NAM', 'NA', '19',13,13),
('南極', '南極', 'Antarctica', 'Antarctica', 'なし', '010', 'ATA', 'AQ', '21',13,13),
('ニウエ', 'ニウエ', 'Niue', 'Member of five UN specialized agencies', 'アロフィ', '570', 'NIU', 'NU', '20',13,13),
('ニカラグア', 'ニカラグア共和国', 'Nicaragua', 'Republic of Nicaragua', 'マナグア', '558', 'NIC', 'NI', '13',13,13),
('ニジェール', 'ニジェール共和国', 'Niger', 'Republic of Niger', 'ニアメ', '562', 'NER', 'NE', '18',13,13),
('西サハラ', '西サハラ', 'Western Sahara', 'Sahrawi Arab Democratic Republic', 'アイウン', '732', 'ESH', 'EH', '17',13,13),
('日本', '日本国', 'Japan', 'Japan', '東京', '392', 'JPN', 'JP', '01',13,13),
('ニューカレドニア', 'ニューカレドニア', 'New Caledonia', 'New Caledonia', 'ヌメア', '540', 'NCL', 'NC', '20',13,13),
('ニュージーランド', 'ニュージーランド', 'New Zealand', 'New Zealand', 'ウェリントン', '554', 'NZL', 'NZ', '20',13,13),
('ネパール', 'ネパール連邦民主共和国', 'Nepal', 'Federal Democratic Republic of Nepal', 'カトマンズ', '524', 'NPL', 'NP', '03',13,13),
('ノーフォーク島', 'ノーフォーク島', 'Norfolk Island', 'Norfolk Island', 'キングストン', '574', 'NFK', 'NF', '20',13,13),
('ノルウェー', 'ノルウェー王国', 'Norway', 'Kingdom of Norway', 'オスロ', '578', 'NOR', 'NO', '09',13,13),
('ハード島とマクドナルド諸島', 'ハード島とマクドナルド諸島', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'なし', '334', 'HMD', 'HM', '04',13,13),
('バーレーン', 'バーレーン王国', 'Bahrain', 'Kingdom of Bahrain', 'マナーマ', '048', 'BHR', 'BH', '06',13,13),
('ハイチ', 'ハイチ共和国', 'Haiti', 'Republic of Haiti', 'ポルトープランス', '332', 'HTI', 'HT', '13',13,13),
('パキスタン', 'パキスタン・イスラム共和国', 'Pakistan', 'Islamic Republic of Pakistan', 'イスラマバード', '586', 'PAK', 'PK', '03',13,13),
('バチカン', 'バチカン市国', 'Vatican City', 'Vatican City State', 'なし', '336', 'VAT', 'VA', '10',13,13),
('パナマ', 'パナマ共和国', 'Panama', 'Republic of Panama', 'パナマシティ', '591', 'PAN', 'PA', '13',13,13),
('バヌアツ', 'バヌアツ共和国', 'Vanuatu', 'Republic of Vanuatu', 'ポートビラ', '548', 'VUT', 'VU', '20',13,13),
('バハマ', 'バハマ国', 'Bahamas, The', 'Commonwealth of The Bahamas', 'ナッソー', '044', 'BHS', 'BS', '13',13,13),
('パプアニューギニア', 'パプアニューギニア独立国', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'ポートモレスビー', '598', 'PNG', 'PG', '20',13,13),
('バミューダ', 'バミューダ', 'Bermuda', 'Bermuda', 'ハミルトン', '060', 'BMU', 'BM', '13',13,13),
('パラオ', 'パラオ共和国', 'Palau', 'Republic of Palau', 'マルキョク', '585', 'PLW', 'PW', '20',13,13),
('パラグアイ', 'パラグアイ共和国', 'Paraguay', 'Republic of Paraguay', 'アスンシオン', '600', 'PRY', 'PY', '14',13,13),
('バルバドス', 'バルバドス', 'Barbados', 'Barbados', 'ブリッジタウン', '052', 'BRB', 'BB', '13',13,13),
('パレスチナ', 'パレスチナ', 'Palestine', 'State of Palestine', '東エルサレム', '275', 'PSE', 'PS', '06',13,13),
('ハンガリー', 'ハンガリー', 'Hungary', 'Hungary', 'ブダペスト', '348', 'HUN', 'HU', '08',13,13),
('バングラデシュ', 'バングラデシュ人民共和国', 'Bangladesh', 'People''s Republic of Bangladesh', 'ダッカ', '050', 'BGD', 'BD', '03',13,13),
('東ティモール', '東ティモール民主共和国', 'East Timor', 'Democratic Republic of Timor-Leste', 'ディリ', '626', 'TLS', 'TL', '02',13,13),
('ピトケアン', 'ピトケアン', 'Pitcairn', 'Pitcairn', 'アダムスタウン', '612', 'PCN', 'PN', '20',13,13),
('フィジー', 'フィジー共和国', 'Fiji', 'Republic of Fiji', 'スバ', '242', 'FJI', 'FJ', '20',13,13),
('フィリピン', 'フィリピン共和国', 'Philippines', 'Republic of the Philippines', 'マニラ', '608', 'PHL', 'PH', '02',13,13),
('フィンランド', 'フィンランド共和国', 'Finland', 'Republic of Finland', 'ヘルシンキ', '246', 'FIN', 'FI', '09',13,13),
('ブータン', 'ブータン王国', 'Bhutan', 'Kingdom of Bhutan', 'ティンプー', '064', 'BTN', 'BT', '03',13,13),
('ブーベ島', 'ブーベ島', 'Bouvet Island', 'Bouvet Island', 'なし', '074', 'BVT', 'BV', '21',13,13),
('プエルトリコ', 'プエルトリコ自治連邦区', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'サンフアン', '630', 'PRI', 'PR', '13',13,13),
('フェロー諸島', 'フェロー諸島', 'Faroe Islands', 'Faroe Islands', 'トースハウン', '234', 'FRO', 'FO', '09',13,13),
('フォークランド諸島', 'フォークランド（マルビナス）諸島', 'Falkland Islands', 'Falkland Islands (Malvinas)', 'スタンリー', '238', 'FLK', 'FK', '14',13,13),
('ブラジル', 'ブラジル連邦共和国', 'Brazil', 'Federative Republic of Brazil', 'ブラジリア', '076', 'BRA', 'BR', '14',13,13),
('フランス', 'フランス共和国', 'France', 'French Republic', 'パリ', '250', 'FRA', 'FR', '10',13,13),
('フランス領南方・南極地域', 'フランス領南方・南極地域', 'French Southern Territories', 'French Southern Territories', 'ポルトーフランセ', '260', 'ATF', 'TF', '04',13,13),
('ブルガリア', 'ブルガリア共和国', 'Bulgaria', 'Republic of Bulgaria', 'ソフィア', '100', 'BGR', 'BG', '08',13,13),
('ブルキナファソ', 'ブルキナファソ', 'Burkina Faso', 'Burkina Faso', 'ワガドゥグー', '854', 'BFA', 'BF', '17',13,13),
('ブルネイ', 'ブルネイ・ダルサラーム国', 'Brunei', 'Nation of Brunei, the Abode of Peace', 'バンダルスリブガワン', '096', 'BRN', 'BN', '02',13,13),
('ブルンジ', 'ブルンジ共和国', 'Burundi', 'Republic of Burundi', 'ギテガ', '108', 'BDI', 'BI', '18',13,13),
('ベトナム', 'ベトナム社会主義共和国', 'Vietnam', 'Socialist Republic of Vietnam', 'ハノイ', '704', 'VNM', 'VN', '02',13,13),
('ベナン', 'ベナン共和国', 'Benin', 'Republic of Benin', 'ポルトノボ', '204', 'BEN', 'BJ', '17',13,13),
('ベネズエラ', 'ベネズエラ・ボリバル共和国', 'Venezuela', 'Bolivarian Republic of Venezuela', 'カラカス', '862', 'VEN', 'VE', '14',13,13),
('ベラルーシ', 'ベラルーシ共和国', 'Belarus', 'Republic of Belarus', 'ミンスク', '112', 'BLR', 'BY', '08',13,13),
('ベリーズ', 'ベリーズ', 'Belize', 'Belize', 'ベルモパン', '084', 'BLZ', 'BZ', '13',13,13),
('ペルー', 'ペルー共和国', 'Peru', 'Republic of Peru', 'リマ', '604', 'PER', 'PE', '14',13,13),
('ベルギー', 'ベルギー王国', 'Belgium', 'Kingdom of Belgium', 'ブリュッセル', '056', 'BEL', 'BE', '10',13,13),
('ポーランド', 'ポーランド共和国', 'Poland', 'Republic of Poland', 'ワルシャワ', '616', 'POL', 'PL', '08',13,13),
('ボスニア・ヘルツェゴビナ', 'ボスニア・ヘルツェゴビナ', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'サラエヴォ', '070', 'BIH', 'BA', '08',13,13),
('ボツワナ', 'ボツワナ共和国', 'Botswana', 'Republic of Botswana', 'ハボローネ', '072', 'BWA', 'BW', '19',13,13),
('ボネール、シント・ユースタティウス及びサバ', 'ボネール、シント・ユースタティウス及びサバ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'クラレンダイク', '535', 'BES', 'BQ', '13',13,13),
('ポリネシア', 'フランス領ポリネシア', 'French Polynesia', 'French Polynesia', 'パペーテ', '258', 'PYF', 'PF', '20',13,13),
('ボリビア', 'ボリビア多民族国', 'Bolivia', 'Plurinational State of Bolivia', 'スクレ', '068', 'BOL', 'BO', '14',13,13),
('ポルトガル', 'ポルトガル共和国', 'Portugal', 'Portuguese Republic', 'リスボン', '620', 'PRT', 'PT', '10',13,13),
('香港', '中華人民共和国香港特別行政区', 'Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', '金鐘添馬', '344', 'HKG', 'HK', '01',13,13),
('ホンジュラス', 'ホンジュラス共和国', 'Honduras', 'Republic of Honduras', 'テグシガルパ', '340', 'HND', 'HN', '13',13,13),
('マーシャル諸島', 'マーシャル諸島共和国', 'Marshall Islands', 'Republic of the Marshall Islands', 'マジュロ', '584', 'MHL', 'MH', '20',13,13),
('マカオ', '中華人民共和国マカオ特別行政区', 'Macau', 'Macao Special Administrative Region of the People''s Republic of China', '花地瑪堂区', '446', 'MAC', 'MO', '01',13,13),
('マダガスカル', 'マダガスカル共和国', 'Madagascar', 'Republic of Madagascar', 'アンタナナリボ', '450', 'MDG', 'MG', '04',13,13),
('マヨット', 'マヨット', 'Mayotte', 'Mayotte', 'マムズ', '175', 'MYT', 'YT', '04',13,13),
('マラウイ', 'マラウイ共和国', 'Malawi', 'Republic of Malawi', 'リロングウェ', '454', 'MWI', 'MW', '19',13,13),
('マリ', 'マリ共和国', 'Mali', 'Republic of Mali', 'バマコ', '466', 'MLI', 'ML', '17',13,13),
('マルタ', 'マルタ共和国', 'Malta', 'Republic of Malta', 'バレッタ', '470', 'MLT', 'MT', '11',13,13),
('マルティニーク', 'マルティニーク', 'Martinique', 'Martinique', 'フォール＝ド＝フランス', '474', 'MTQ', 'MQ', '13',13,13),
('マレーシア', 'マレーシア', 'Malaysia', 'Malaysia', 'クアラルンプール', '458', 'MYS', 'MY', '02',13,13),
('マン島', 'マン島', 'Isle of Man', 'Isle of Man', 'ダグラス', '833', 'IMN', 'IM', '10',13,13),
('ミクロネシア', 'ミクロネシア連邦', 'Micronesia', 'Federated States of Micronesia', 'パリキール', '583', 'FSM', 'FM', '20',13,13),
('南アフリカ', '南アフリカ共和国', 'South Africa', 'Republic of South Africa', 'プレトリア（行政首都）、ケープタウン（立法首都）、ブルームフォンテン（司法首都）', '710', 'ZAF', 'ZA', '19',13,13),
('南スーダン', '南スーダン共和国', 'South Sudan', 'Republic of South Sudan', 'ジュバ', '728', 'SSD', 'SS', '16',13,13),
('ミャンマー', 'ミャンマー連邦共和国', 'Myanmar', 'Republic of the Union of Myanmar', 'ネピドー', '104', 'MMR', 'MM', '02',13,13),
('メキシコ', 'メキシコ合衆国', 'Mexico', 'United Mexican States', 'メキシコシティ', '484', 'MEX', 'MX', '13',13,13),
('モーリシャス', 'モーリシャス共和国', 'Mauritius', 'Republic of Mauritius', 'ポートルイス', '480', 'MUS', 'MU', '19',13,13),
('モーリタニア', 'モーリタニア・イスラム共和国', 'Mauritania', 'Islamic Republic of Mauritania', 'ヌアクショット', '478', 'MRT', 'MR', '17',13,13),
('モザンビーク', 'モザンビーク共和国', 'Mozambique', 'Republic of Mozambique', 'マプト', '508', 'MOZ', 'MZ', '19',13,13),
('モナコ', 'モナコ公国', 'Monaco', 'Principality of Monaco', 'なし', '492', 'MCO', 'MC', '10',13,13),
('モルディブ', 'モルディブ共和国', 'Maldives', 'Republic of Maldives', 'マレ', '462', 'MDV', 'MV', '04',13,13),
('モルドバ', 'モルドバ共和国', 'Moldova', 'Republic of Moldova', 'キシナウ', '498', 'MDA', 'MD', '08',13,13),
('モロッコ', 'モロッコ王国', 'Morocco', 'Kingdom of Morocco', 'ラバト', '504', 'MAR', 'MA', '15',13,13),
('モンゴル', 'モンゴル国', 'Mongolia', 'Mongolia', 'ウランバートル', '496', 'MNG', 'MN', '01',13,13),
('モンテネグロ', 'モンテネグロ', 'Montenegro', 'Montenegro', 'ポドゴリツァ', '499', 'MNE', 'ME', '08',13,13),
('モントセラト', 'モントセラト', 'Montserrat', 'Montserrat', 'リトルベイ', '500', 'MSR', 'MS', '13',13,13),
('ヨルダン', 'ヨルダン・ハシミテ王国', 'Jordan', 'Hashemite Kingdom of Jordan', 'アンマン', '400', 'JOR', 'JO', '06',13,13),
('ラオス', 'ラオス人民民主共和国', 'Laos', 'Lao People''s Democratic Republic', 'ビエンチャン', '418', 'LAO', 'LA', '02',13,13),
('ラトビア', 'ラトビア共和国', 'Latvia', 'Republic of Latvia', 'リガ', '428', 'LVA', 'LV', '08',13,13),
('リトアニア', 'リトアニア共和国', 'Lithuania', 'Republic of Lithuania', 'ヴィリニュス', '440', 'LTU', 'LT', '08',13,13),
('リビア', 'リビア', 'Libya', 'State of Libya', 'トリポリ', '434', 'LBY', 'LY', '15',13,13),
('リヒテンシュタイン', 'リヒテンシュタイン公国', 'Liechtenstein', 'Principality of Liechtenstein', 'ファドゥーツ', '438', 'LIE', 'LI', '10',13,13),
('リベリア', 'リベリア共和国', 'Liberia', 'Republic of Liberia', 'モンロビア', '430', 'LBR', 'LR', '17',13,13),
('ルーマニア', 'ルーマニア', 'Romania', 'Romania', 'ブカレスト', '642', 'ROU', 'RO', '08',13,13),
('ルクセンブルク', 'ルクセンブルク大公国', 'Luxembourg', 'Grand Duchy of Luxembourg', 'ルクセンブルク', '442', 'LUX', 'LU', '10',13,13),
('ルワンダ', 'ルワンダ共和国', 'Rwanda', 'Republic of Rwanda', 'キガリ', '646', 'RWA', 'RW', '18',13,13),
('レソト', 'レソト王国', 'Lesotho', 'Kingdom of Lesotho', 'マセル', '426', 'LSO', 'LS', '19',13,13),
('レバノン', 'レバノン共和国', 'Lebanon', 'Lebanese Republic', 'ベイルート', '422', 'LBN', 'LB', '06',13,13),
('レユニオン', 'レユニオン', 'Réunion', 'Réunion', 'サン＝ドニ', '638', 'REU', 'RE', '04',13,13),
('ロシア', 'ロシア連邦', 'Russia', 'Russian Federation', 'モスクワ', '643', 'RUS', 'RU', '07',13,13)
;

